### ISSUE TITLE
No module named `result_file_functions` and other modules.

### ISSUE THREAD

**Issue by siedentop** [danoneata/fisher_vectors#1]
The below test shows that importing `fisher_vectors/evaluation/hollywood2_evaluation.py` is impossible because there is no module `result_file_functions`.

Also missing (run `$nosetests` in root folder) are modules `dataset`, `ekovof.dense.dense_distances`, and `video_vwgeo`.

It would be very nice, if you could provide these please.

```
$ nosetests evaluation/hollywood2_evaluation.py
E
======================================================================
ERROR: Failure: ImportError (No module named result_file_functions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/export/home/csiedent/.local/lib/python2.7/site-packages/nose-1.3.3-py2.7.egg/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/export/home/csiedent/.local/lib/python2.7/site-packages/nose-1.3.3-py2.7.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/export/home/csiedent/.local/lib/python2.7/site-packages/nose-1.3.3-py2.7.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/export/home/csiedent/src/fisher_vectors/fisher_vectors/evaluation/__init__.py", line 2, in <module>
    from .hollywood2_evaluation import Hollywood2Evaluation
  File "/export/home/csiedent/src/fisher_vectors/fisher_vectors/evaluation/hollywood2_evaluation.py", line 10, in <module>
    from utils import average_precision
  File "/export/home/csiedent/src/fisher_vectors/fisher_vectors/evaluation/utils.py", line 1, in <module>
    import result_file_functions
ImportError: No module named result_file_functions

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
```

**Comment by siedentop** [comment]
Closing as too old.
